server:
  port: 8445
spring:
  datasource:
    url: jdbc:mysql://125.64.103.212:12006/online-mall?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    data-username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: 125.64.103.212
    port: 12079
    password:
    database: 0
