server:
  port: 8445
spring:
  datasource:
    url: jdbc:mysql://125.64.103.212:12006/online-mall?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    data-username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: 125.64.103.212
    port: 12079
    password:
    database: 0

token:
  header: Authorization #自定义token标识
  secret: zaqwsxcderfvbgtyhnmjuiklop #密钥
  expireTime: 3600000 #过期时间(30分钟)

logging:
  # 对指定的包调整日志的级别(trace、debug、info、warn、error)
  level:
    com:
      van: trace


secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /minio/upload
